name = "go2asia-referral-service"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.staging]
name = "go2asia-referral-service-staging"
vars = { 
  NODE_ENV = "staging",
}

[env.production]
name = "go2asia-referral-service-prod"
vars = { 
  NODE_ENV = "production",
}

[observability]
enabled = true

[observability.logs]
enabled = true
persist = true
invocation_logs = true

